import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="fixed top-0 left-0 right-0   z-50">
          <Navbar></Navbar>
        </div>
        <main className={" bg-primary " }>{children}</main>
      </body>
    </html>
  );
}
